<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>Hemisphera.Hulp.WebApp</AssemblyName>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <RootNamespace>Hemisphera.Hulp.WebApp</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hsp.Osc" Version="0.0.29" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Hemisphera.Hulp.Shared\Hemisphera.Hulp.Shared.csproj" />
    </ItemGroup>

</Project>
