<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <RootNamespace>ReaParamView.WebApp</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hsp.Osc" Version="0.0.27" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Hemisphera.Hulp.Types\Hemisphera.Hulp.Types.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Components\Components\Knob.razor" />
    </ItemGroup>

</Project>
